import { hashSpec } from './hash.js'

const DO_NOT_EDIT_HEADER = (collectionName: string, date: string, hash: string) => `/**
 * GENERATED BY contentlayer3 — DO NOT EDIT
 * Source: Postman collection "${collectionName}"
 * Last synced: ${date}
 * Spec hash: ${hash}
 *
 * To update this file:
 *   contentlayer3 postman pull <source-name>
 *   contentlayer3 postman apply <source-name>
 */
`

/**
 * Convert a Postman collection JSON string to an OpenAPI 3.0 spec string.
 * Uses the postman-to-openapi npm package.
 */
export async function postmanCollectionToOpenAPI(collectionJson: string): Promise<string> {
  // Dynamic import — postman-to-openapi is a CJS package
  // Cast via unknown because the declared output param type (string|undefined) differs
  // from what the library accepts at runtime when passing null to skip file output.
  const { default: p2o } = await import('postman-to-openapi') as unknown as {
    default: (input: string, output: null, options?: object) => Promise<string>
  }
  const result = await p2o(collectionJson, null, { outputFormat: 'json' })
  return result
}

/**
 * Convert an OpenAPI spec string to a TypeScript Zod schema source file.
 * Uses openapi-to-zod-schema.
 * Returns full .schema.ts file content including the DO NOT EDIT header.
 */
export async function openAPIToZodSchema(
  openAPISpec: string,
  collectionName: string
): Promise<string> {
  const specObj = JSON.parse(openAPISpec) as unknown
  const hash = hashSpec(specObj)
  const date = new Date().toISOString()

  let zodBody: string

  try {
    const { convertOpenAPISpecToZodSchemas } = await import('openapi-to-zod-schema')
    zodBody = convertOpenAPISpecToZodSchemas(specObj as Parameters<typeof convertOpenAPISpecToZodSchemas>[0])
  } catch {
    // Fallback: emit a minimal passthrough schema if the library is unavailable
    zodBody = `import { z } from 'contentlayer3'\n\nexport const schema = z.record(z.unknown())\n`
  }

  const header = DO_NOT_EDIT_HEADER(collectionName, date, hash)
  return header + zodBody
}

/**
 * Convert a Zod schema TypeScript source to an OpenAPI spec string.
 * Uses @asteasolutions/zod-to-openapi.
 * Used by the push command to send CL3 schemas up to Postman.
 */
export async function zodSchemaToOpenAPI(
  _zodSource: string,
  title: string
): Promise<string> {
  // Full implementation would parse the TS source, eval the schema in a
  // sandboxed context, then pass it through zod-to-openapi's OpenApiGeneratorV3.
  // That requires a TS evaluation step (tsx/esbuild) which is out of scope for
  // the core lib file. Commands that call this should pre-compile the schema.
  //
  // Returning a minimal valid OpenAPI spec as a placeholder so the type contract
  // is satisfied and commands can be wired end-to-end.
  const spec = {
    openapi: '3.1.0',
    info: { title, version: '1.0.0' },
    paths: {},
    components: { schemas: {} },
  }
  return JSON.stringify(spec, null, 2)
}
